name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create build directory
      run: mkdir -p build

    - name: Build AE addon
      run: python util/build-ae.py

    - name: Build Blender addon
      run: python util/build-blender.py

    - name: Display structure of downloaded files
      run: ls -l
      working-directory: ./build

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./build/*"
        draft: true
